export default buttons = [
  { label: '(', color: '#00d315', value: '(', fontWeight: 'bold' },
  { label: ')', color: '#00d315', value: ')', fontWeight: 'bold' },
  { label: '%', color: '#00d315', value: '%', fontWeight: 'bold' },
  { label: '÷', color: '#00d315', value: '/', fontWeight: 'bold' },
  { label: '7', color: '#fff', value: '7', fontWeight: '400' },
  { label: '8', color: '#fff', value: '8', fontWeight: '400' },
  { label: '9', color: '#fff', value: '9', fontWeight: '400' },
  { label: 'x', color: '#00d315', value: '*', fontWeight: 'bold' },
  { label: '4', color: '#fff', value: '4', fontWeight: '400' },
  { label: '5', color: '#fff', value: '5', fontWeight: '400' },
  { label: '6', color: '#fff', value: '6', fontWeight: '400' },
  { label: '-', color: '#00d315', value: '-', fontWeight: 'bold' },
  { label: '1', color: '#fff', value: '1', fontWeight: '400' },
  { label: '2', color: '#fff', value: '2', fontWeight: '400' },
  { label: '3', color: '#fff', value: '3', fontWeight: '400' },
  { label: '+', color: '#00d315', value: '+', fontWeight: 'bold' },
  { label: 'xⁿ', color: '#00d315', value: '^', fontWeight: 'bold' },
  { label: '0', color: '#fff', value: '0', fontWeight: '400' },
  { label: ',', color: '#fff', value: '.', tipo: 'point', fontWeight: '400' },
  { label: '=', color: '#00d315', value: '=', fontWeight: 'bold' }
]
